[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[functions]
directory = "functions"
external_node_modules = [
  "better-sqlite3", 
  "@pinecone-database/pinecone", 
  "openai", 
  "resend", 
  "stripe", 
  "zod"
]
